[versions]
archetype = "0.11.0-SNAPSHOT"
java = "21"

springBoot = "4.0.1"
springCloud = "2025.1.0"

lombok = "1.18.42"
spotless = "8.1.0"

testcontainers = "2.0.3"
junit = "5.14.1"

[libraries]
# Spring Boot starters (used by starters, not necessarily by services directly)
bootAutoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
bootConfigurationProcessor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
bootStarter = { module = "org.springframework.boot:spring-boot-starter" }
bootStarterWeb = { module = "org.springframework.boot:spring-boot-starter-web" }
bootStarterActuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }

bootStarterSecurity = { module = "org.springframework.boot:spring-boot-starter-security" }
bootStarterOauth2ResourceServer = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
bootStarterOauth2Client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }

springCloudBom = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloud" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# Testing
junitBom = { module = "org.junit:junit-bom", version.ref = "junit" }
testcontainersBom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
